# Generated by Django 5.0.4 on 2024-05-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControlePonto',
        ),
        migrations.RemoveField(
            model_name='documentoauditoria',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='documentoauditoria',
            name='colaborador',
        ),
        migrations.RemoveField(
            model_name='documentoauditoria',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='documentoauditoria',
            name='regional',
        ),
        migrations.RemoveField(
            model_name='documentoauditoria',
            name='status',
        ),
        migrations.RemoveField(
            model_name='documentoauditoria',
            name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='documentoauditoria',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='documentoexistente',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='documentoexistente',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='documentoexistente',
            name='regional',
        ),
        migrations.RemoveField(
            model_name='documentoexistente',
            name='status',
        ),
        migrations.RemoveField(
            model_name='documentoexistente',
            name='unidade',
        ),
        migrations.DeleteModel(
            name='DocumentoExistenteAuditoria',
        ),
        migrations.DeleteModel(
            name='ResultadoDossie',
        ),
        migrations.DeleteModel(
            name='SistemaPonto',
        ),
        migrations.AlterField(
            model_name='documentopendente',
            name='situacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='DocumentoAuditoria',
        ),
        migrations.DeleteModel(
            name='DocumentoExistente',
        ),
    ]
