# Generated by Django 5.0.4 on 2024-05-07 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0002_delete_controleponto_remove_documentoauditoria_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomingosFeriados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja', models.CharField(max_length=255)),
                ('data_documento', models.DateField(blank=True, null=True)),
                ('nome_documento', models.CharField(max_length=255)),
                ('link_documento', models.CharField(max_length=255)),
                ('data_upload', models.DateField()),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documento.empresa')),
            ],
            options={
                'db_table': 'domingosferiados',
            },
        ),
    ]
