# Generated by Django 5.0.4 on 2024-05-07 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0003_domingosferiados'),
    ]

    operations = [
        migrations.AddField(
            model_name='domingosferiados',
            name='regional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documento.regional'),
        ),
    ]
