# Generated by Django 5.0.4 on 2024-05-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0004_domingosferiados_regional'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentovencido',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
