# constants.py

LISTA_PROFISSOES = (
    ("advogado", "Advogado"),
    ("engenheiro", "Engenheiro"),
    ("médico", "Médico"),
    ("professor", "Professor"),
    ("enfermeiro", "Enfermeiro"),
    ("analista_de_sistemas", "Analista de Sistemas"),
    ("contador", "Contador"),
    ("arquiteto", "Arquiteto"),
    ("designer", "Designer"),
    ("programador", "Programador"),
    ("administrador", "Administrador"),
    ("psicólogo", "Psicólogo"),
    ("farmacêutico", "Farmacêutico"),
    ("nutricionista", "Nutricionista"),
    ("dentista", "Dentista"),
    ("veterinário", "Veterinário"),
    ("jornalista", "Jornalista"),
    ("eletricista", "Eletricista"),
    ("motorista", "Motorista"),
    ("piloto", "Piloto"),
    ("designer_gráfico", "Designer Gráfico"),
    ("analista_financeiro", "Analista Financeiro"),
    ("consultor", "Consultor"),
    ("terapeuta", "Terapeuta"),
    ("fisioterapeuta", "Fisioterapeuta"),
    ("cientista", "Cientista"),
    ("biólogo", "Biólogo"),
    ("químico", "Químico"),
    ("fotógrafo", "Fotógrafo"),
    ("cineasta", "Cineasta"),
    ("artista", "Artista"),
    ("escritor", "Escritor"),
    ("astrônomo", "Astrônomo"),
    ("geólogo", "Geólogo"),
    ("pescador", "Pescador"),
    ("marceneiro", "Marceneiro"),
    ("pedreiro", "Pedreiro"),
    ("pintor", "Pintor"),
    ("mecânico", "Mecânico"),
    ("padeiro", "Padeiro"),
    ("chef", "Chef"),
    ("garçom", "Garçom"),
    ("atendente", "Atendente"),
    ("recepcionista", "Recepcionista"),
    ("motorista_de_ônibus", "Motorista de Ônibus"),
    ("policial", "Policial"),
    ("bombeiro", "Bombeiro"),
    ("militar", "Militar"),
    ("ator", "Ator"),
    ("cantor", "Cantor"),
    ("dançarino", "Dançarino"),
    ("atleta", "Atleta"),
    ("escultor", "Escultor"),
    ("historiador", "Historiador"),
    ("economista", "Economista"),
    ("sociólogo", "Sociólogo"),
    ("psiquiatra", "Psiquiatra"),
    ("engenheiro_civil", "Engenheiro Civil"),
    ("engenheiro_mecânico", "Engenheiro Mecânico"),
    ("engenheiro_elétrico", "Engenheiro Elétrico"),
    ("engenheiro_de_software", "Engenheiro de Software"),
)

